# serverless.yml
plugins:
    - serverless-offline
    - serverless-dotenv-plugin

service: apollo-lambda
provider:
    name: aws
    region: eu-west-1
    runtime: nodejs8.10
    iamRoleStatements:
        - Effect: "Allow"
          Action: s3:*
          Resource: arn:aws:s3:::ehe-development/*
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: "*"          
functions:
    graphql:
        handler: lambdas/graphql.graphqlHandler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: true
            - http:
                  path: graphql
                  method: get
                  cors: true
